name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-targets
      - name: Run tests
        run: cargo test -- -Z unstable-options --format json --report-time | cargo run
      - name: Run clippy
        run: cargo clippy
